openapi: 3.1.0
info:
  description: Figshare apiv2. Using OpenApi 3.1.0
  title: Figshare API
  version: 2.0.0
servers:
- url: https://api.figshare.com/v2
paths:
  /articles:
    get:
      description: Returns a list of public articles
      operationId: articles_list
      parameters:
      - description: "Unique hash used for bypassing the item retrieval limit of 9,000\
          \ entities. When using this parameter, please note that the offset parameter\
          \ will not be available, but the limit parameter will still work as expected."
        explode: false
        in: header
        name: X-Cursor
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: Page number. Used for pagination with page_size
        explode: true
        in: query
        name: page
        required: false
        schema:
          format: int64
          maximum: 5000
          minimum: 1
          type: integer
        style: form
      - description: The number of results included on a page. Used for pagination
          with page
        explode: true
        in: query
        name: page_size
        required: false
        schema:
          default: 10
          format: int64
          maximum: 1000
          minimum: 1
          type: integer
        style: form
      - description: Number of results included on a page. Used for pagination with
          query
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int64
          maximum: 1000
          minimum: 1
          type: integer
        style: form
      - description: Where to start the listing (the offset of the first result).
          Used for pagination with limit
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int64
          maximum: 5000
          minimum: 0
          type: integer
        style: form
      - description: The field by which to order. Default varies by endpoint/resource.
        explode: true
        in: query
        name: order
        required: false
        schema:
          default: published_date
          enum:
          - published_date
          - created_date
          - modified_date
          - views
          - shares
          - downloads
          - cites
          type: string
        style: form
      - explode: true
        in: query
        name: order_direction
        required: false
        schema:
          default: desc
          enum:
          - asc
          - desc
          type: string
        style: form
      - description: only return articles from this institution
        explode: true
        in: query
        name: institution
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: Filter by article publishing date. Will only return articles
          published after the date. date(ISO 8601) YYYY-MM-DD or date-time(ISO 8601)
          YYYY-MM-DDTHH:mm:ssZ
        explode: true
        in: query
        name: published_since
        required: false
        schema:
          type: string
        style: form
      - description: Filter by article modified date. Will only return articles published
          after the date. date(ISO 8601) YYYY-MM-DD or date-time(ISO 8601) YYYY-MM-DDTHH:mm:ssZ
        explode: true
        in: query
        name: modified_since
        required: false
        schema:
          type: string
        style: form
      - description: only return articles from this group
        explode: true
        in: query
        name: group
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: Deprecated by related materials. Only return articles with this
          resource_doi
        explode: true
        in: query
        name: resource_doi
        required: false
        schema:
          type: string
        style: form
      - description: "Only return articles with the respective type. Mapping for item_type\
          \ is: 1 - Figure, 2 - Media, 3 - Dataset, 5 - Poster, 6 - Journal contribution,\
          \ 7 - Presentation, 8 - Thesis, 9 - Software, 11 - Online resource, 12 -\
          \ Preprint, 13 - Book, 14 - Conference contribution, 15 - Chapter, 16 -\
          \ Peer review, 17 - Educational resource, 18 - Report, 19 - Standard, 20\
          \ - Composition, 21 - Funding, 22 - Physical object, 23 - Data management\
          \ plan, 24 - Workflow, 25 - Monograph, 26 - Performance, 27 - Event, 28\
          \ - Service, 29 - Model"
        explode: true
        in: query
        name: item_type
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: only return articles with this doi
        explode: true
        in: query
        name: doi
        required: false
        schema:
          type: string
        style: form
      - description: only return articles with this handle
        explode: true
        in: query
        name: handle
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Article'
                type: array
          description: OK. An array of articles
          headers:
            X-Cursor:
              description: "Unique hash used for bypassing the item retrieval limit\
                \ of 9,000 entities."
              explode: false
              schema:
                nullable: true
                type: string
              style: simple
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity. Syntax is correct but one of the parameters
            isn't correctly processed
        "500":
          description: Internal Server Error
      security: []
      summary: Public Articles
      tags:
      - articles
  /articles/{article_id}:
    get:
      description: View an article
      operationId: article_details
      parameters:
      - description: Article Unique identifier
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleComplete'
          description: OK. Article representation
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security: []
      summary: View article details
      tags:
      - articles
  /total/article/{article_id}:
    get:
      description: "View article total downloads, views"
      operationId: total
      parameters:
      - description: Article Unique identifier
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalArticle'
          description: OK. Article representation
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security: []
      servers:
      - url: https://stats.figshare.com
      summary: "View article total downloads, views"
      tags:
      - articles
  /{institution}/total/article/{article_id}:
    get:
      description: "View article total downloads, views"
      operationId: total_ins
      parameters:
      - description: institution
        explode: false
        in: path
        name: institution
        required: true
        schema:
          type: string
        style: simple
      - description: Article Unique identifier
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalArticle'
          description: OK. Article representation
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security: []
      servers:
      - url: https://stats.figshare.com
      summary: "View article total downloads, views"
      tags:
      - articles
  /4tu/total/article/{article_id}:
    get:
      description: "View article total downloads, views"
      operationId: crawl_total_article_4tu
      parameters:
      - description: Article Unique identifier
        explode: false
        in: path
        name: article_id
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalArticle'
          description: OK. Article representation
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security: []
      servers:
      - url: https://stats.figshare.com
      summary: "View article total downloads, views"
      tags:
      - articles
  /viz/data/publication/for/aggregated-citations.json:
    get:
      description: Get article aggregated citations
      operationId: get_aggregated_citations
      parameters:
      - description: Article DOI
        explode: true
        in: query
        name: and_subset_figshare_doi
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: viz-st:aggr
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: np
        required: false
        schema:
          type: string
        style: form
      - description: 必须包含 session 和 uber_auth_tkt
        explode: false
        in: header
        name: Cookie
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: x-csrf-token
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: User-Agent
        required: false
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Referer
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedCitations'
          description: OK. Article representation
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security: []
      servers:
      - url: https://app.dimensions.ai
      summary: Get article aggregated citations
      tags:
      - articles
components:
  schemas:
    Article:
      example:
        url_private_html: https://figshare.com/account/articles/1434614
        thumb: https://ndownloader.figshare.com/files/123456789/preview/12345678/thumb.png
        url_public_html: https://figshare.com/articles/media/Test_article_title/1434614
        url_private_api: https://api.figshare.com/account/articles/1434614
        handle: 111184/figshare.1234
        title: Test article title
        modified_date: 2017-05-18T11:49:03Z
        defined_type_name: media
        url: http://api.figshare.com/articles/1434614
        defined_type: 3
        group_id: 1234
        resource_doi: ""
        resource_title: ""
        id: 1434614
        url_public_api: https://api.figshare.com/articles/1434614
        created_date: 2017-05-18T11:49:03Z
        published_date: 2015-12-31T23:59:59.000Z
        doi: 10.6084/m9.figshare.1434614
      properties:
        id:
          description: Unique identifier for article
          example: 1434614
          format: int64
          type: integer
        title:
          description: Title of article
          example: Test article title
          type: string
        doi:
          description: DOI
          example: 10.6084/m9.figshare.1434614
          type: string
        handle:
          description: Handle
          example: 111184/figshare.1234
          type: string
        group_id:
          description: Group ID
          example: 1234
          type: number
          x-nullable: true
        url:
          description: Api endpoint for article
          example: http://api.figshare.com/articles/1434614
          format: url
          type: string
        url_public_html:
          description: Public site endpoint for article
          example: https://figshare.com/articles/media/Test_article_title/1434614
          format: url
          type: string
        url_public_api:
          description: Public Api endpoint for article
          example: https://api.figshare.com/articles/1434614
          format: url
          type: string
        url_private_html:
          description: Private site endpoint for article
          example: https://figshare.com/account/articles/1434614
          format: url
          type: string
        url_private_api:
          description: Private Api endpoint for article
          example: https://api.figshare.com/account/articles/1434614
          format: url
          type: string
        published_date:
          description: Posted date
          example: 2015-12-31T23:59:59.000Z
          type: string
          x-nullable: true
        thumb:
          description: Thumbnail image
          example: https://ndownloader.figshare.com/files/123456789/preview/12345678/thumb.png
          format: url
          type: string
        defined_type:
          description: Type of article identifier
          example: 3
          format: int64
          type: integer
        defined_type_name:
          description: Name of the article type identifier
          example: media
          type: string
        resource_doi:
          default: ""
          description: "Deprecated by related materials. Not applicable to regular\
            \ users. In a publisher case, this is the publisher article DOI."
          type: string
        resource_title:
          default: ""
          description: "Deprecated by related materials. Not applicable to regular\
            \ users. In a publisher case, this is the publisher article title."
          type: string
        created_date:
          description: Date when article was created
          example: 2017-05-18T11:49:03Z
          type: string
        modified_date:
          description: Date when article was last modified
          example: 2017-05-18T11:49:03Z
          type: string
          x-nullable: true
      required:
      - created_date
      - defined_type
      - defined_type_name
      - doi
      - group_id
      - handle
      - id
      - modified_date
      - published_date
      - resource_doi
      - resource_title
      - thumb
      - title
      - url
      - url_private_api
      - url_private_html
      - url_public_api
      - url_public_html
      x-tag: articles
    ProjectArticle:
      allOf:
      - $ref: '#/components/schemas/Article'
      properties:
        citation:
          description: Article citation
          example: "lilliput, figshare admin (2017): first project item. figshare.\n\
            \ \n Retrieved: 14 01, May 22, 2017 (GMT)"
        confidential_reason:
          description: Confidentiality reason
          example: none
        embargo_type:
          description: Article embargo
          example: article
        is_confidential:
          description: Article Confidentiality
          example: true
        size:
          description: Article size
          example: 69939
          format: int64
        funding:
          description: Article funding
          example: none
        tags:
          description: List of article tags. Keywords can be used instead
          example:
          - t1
          - t2
          - t3
          items: {}
        keywords:
          description: List of article keywords. Tags can be used instead
          example:
          - t1
          - t2
          - t3
          items: {}
        version:
          description: Article version
          example: 1
          format: int64
        is_metadata_record:
          description: True if article has no files
          example: false
        metadata_reason:
          description: Article metadata reason
          example: hosted somewhere else
        status:
          description: Article status
          example: public
        description:
          description: Article description
          example: article description
        is_embargoed:
          description: True if article is embargoed
          example: true
        embargo_date:
          description: Date when embargo lifts
          example: 2017-05-18T11:49:03Z
        is_public:
          description: True if article is published
          example: true
        modified_date:
          description: Date when article was last modified
          example: 2017-05-18T11:49:03Z
        created_date:
          description: Date when article was created
          example: 2017-05-18T11:49:03Z
        has_linked_file:
          description: True if any files are linked to the article
          example: true
        categories:
          description: List of categories selected for the article
          items:
            $ref: '#/components/schemas/Category'
        license:
          $ref: '#/components/schemas/License'
        embargo_title:
          description: Title for embargo
          example: File(s) under embargo
        embargo_reason:
          description: Reason for embargo
          example: not complete
        references:
          description: List of references
          example:
          - http://figshare.com
          - http://figshare.com/api
          items:
            format: url
      required:
      - categories
      - citation
      - confidential_reason
      - created_date
      - description
      - embargo_date
      - embargo_reason
      - embargo_title
      - embargo_type
      - funding
      - has_linked_file
      - is_confidential
      - is_embargoed
      - is_metadata_record
      - is_public
      - keywords
      - license
      - metadata_reason
      - modified_date
      - references
      - size
      - status
      - tags
      - version
      x-tag: articles
    ArticleComplete:
      allOf:
      - $ref: '#/components/schemas/ProjectArticle'
      example:
        figshare_url: http://figshare.com/articles/media/article_name/2000005
        download_disabled: false
        folder_structure:
          "3000002": Test Folder
      properties:
        figshare_url:
          description: Article public url
          example: http://figshare.com/articles/media/article_name/2000005
          format: url
        download_disabled:
          description: "If true, downloading of files for this article is disabled"
          example: false
        folder_structure:
          description: "Mapping of file ids to folder paths, if folders are used"
          example:
            "3000002": Test Folder
      required:
      - download_disabled
      - figshare_url
      x-tag: articles
    Category:
      properties:
        parent_id:
          description: Parent category
          example: 1
          format: int64
          type: integer
        id:
          description: Category id
          example: 11
          format: int64
          type: integer
        title:
          description: Category title
          example: Anatomy
          type: string
        path:
          description: Path to all ancestor ids
          example: /450/1024/6532
          type: string
        source_id:
          description: ID in original standard taxonomy
          example: "300204"
          type: string
        taxonomy_id:
          description: Internal id of taxonomy the category is part of
          example: 4
          format: int64
          type: integer
      required:
      - id
      - parent_id
      - path
      - source_id
      - taxonomy_id
      - title
      x-tag: common
    License:
      properties:
        value:
          description: License value
          example: 1
          format: int64
          type: integer
        name:
          description: License name
          example: CC BY
          type: string
        url:
          description: License url
          example: http://creativecommons.org/licenses/by/4.0/
          format: url
          type: string
      required:
      - name
      - url
      - value
      x-tag: institutions
    TotalArticle:
      example:
        shares: 1434614
        downloads: 1434614
        cites: 1434614
        views: 1434614
      properties:
        downloads:
          description: downloads for article
          example: 1434614
          format: int64
          type: integer
        views:
          description: views for article
          example: 1434614
          format: int64
          type: integer
        shares:
          description: shares for article
          example: 1434614
          format: int64
          type: integer
        cites:
          description: cites for article
          example: 1434614
          format: int64
          type: integer
      x-tag: articles
    AggregatedCitations:
      example:
        navigation:
          data_json: data_json
        results:
        - name:
            label: label
            sublabel: sublabel
          count:
            label: 0
          id: id
        - name:
            label: label
            sublabel: sublabel
          count:
            label: 0
          id: id
      properties:
        navigation:
          $ref: '#/components/schemas/AggregatedCitations_navigation'
        results:
          items:
            $ref: '#/components/schemas/AggregatedCitations_results_inner'
          type: array
      x-tag: articles
    AggregatedCitations_navigation:
      example:
        data_json: data_json
      properties:
        data_json:
          type: string
    AggregatedCitations_results_inner_name:
      example:
        label: label
        sublabel: sublabel
      properties:
        label:
          type: string
        sublabel:
          type: string
    AggregatedCitations_results_inner_count:
      example:
        label: 0
      properties:
        label:
          format: int64
          type: integer
    AggregatedCitations_results_inner:
      example:
        name:
          label: label
          sublabel: sublabel
        count:
          label: 0
        id: id
      properties:
        id:
          type: string
        name:
          $ref: '#/components/schemas/AggregatedCitations_results_inner_name'
        count:
          $ref: '#/components/schemas/AggregatedCitations_results_inner_count'
